 services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # Optional - specify the uid and gid you would like Jellyfin to use instead of root
    user: 1000:1000
    ports:
      - 8096:8096/tcp
      #- 7359:7359/udp
    volumes:
      #- /opt/stacks/jellyfin/config:/config
      #- /opt/stacks/jellyfin/cache:/cache
      - ./jellyfin-config:/config
      - ./jellyfin-cache:/cache
      - ${MEDIA_LOCATION}:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - TZ=${TIMEZONE}
      - /dev/dri:/dev/dri
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode